version: "3"
services:

  elasticsearch:
    container_name: elasticsearch
    ports:
            - '9200:9200'
            - '9300:9300'
    environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
    image: 'elasticsearch:8.8.1'
    networks:
      network_elastic:
        ipv4_address: 10.5.0.3

  kibana:
    image: kibana:8.8.1
    ports:
      - 5601:5601
    networks:
      network_elastic:
        ipv4_address: 10.5.0.4

  
  spark-master:
    image: cluster-apache-spark:3.2.1
    container_name: spark-master
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master
    networks:
      network_elastic:
        ipv4_address: 10.5.0.5

  spark-worker-a:
    image: cluster-apache-spark:3.2.1
    container_name: spark-worker-a
    ports:
      - "9091:8080"
      - "7000:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=4
      - SPARK_WORKER_MEMORY=3G
      - SPARK_DRIVER_MEMORY=3G
      - SPARK_EXECUTOR_MEMORY=3G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-a
    volumes:
       - ./apps:/opt/spark-apps
       - ./data:/opt/spark-data
    networks:
      network_elastic:
        ipv4_address: 10.5.0.6

  spark-worker-b:
    image: cluster-apache-spark:3.2.1
    container_name: spark-worker-b
    ports:
      - "9092:8080"
      - "7001:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=4
      - SPARK_WORKER_MEMORY=3G
      - SPARK_DRIVER_MEMORY=3G
      - SPARK_EXECUTOR_MEMORY=3G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-b
    volumes:
        - ./apps:/opt/spark-apps
        - ./data:/opt/spark-data
    networks:
      network_elastic:
        ipv4_address: 10.5.0.7

networks:
  network_elastic:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16